version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: httpsd-service
      POSTGRES_USER: httpsd-user
      POSTGRES_PASSWORD: root321root
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./dbdata:/var/lib/postgresql/data
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "4343:5432"